import Foundation

enum WineData {
    static let varieties: [String] = [
        "Cabernet Sauvignon",
        "Merlot",
        "Pinot Noir",
        "Syrah",
        "Shiraz",
        "Zinfandel",
        "Malbec",
        "Tempranillo",
        "Sangiovese",
        "Nebbiolo",
        "Grenache",
        "Mourvèdre",
        "Barbera",
        "Petit Verdot",
        "Cabernet Franc",
        "Gamay",
        "Petite Sirah",
        "Carménère",
        "Montepulciano",
        "Primitivo",
        "Chardonnay",
        "Sauvignon Blanc",
        "Riesling",
        "Pinot Grigio",
        "Pinot Gris",
        "Moscato",
        "Gewürztraminer",
        "Viognier",
        "Chenin Blanc",
        "Sémillon",
        "Albariño",
        "Grüner Veltliner",
        "Torrontés",
        "Vermentino",
        "Trebbiano",
        "Prosecco",
        "Champagne Blend",
        "Bordeaux Blend",
        "Rhône Blend",
        "Rosé",
        "Port",
        "Sherry",
        "Sparkling",
        "Other"
    ]

    static let regions: [String] = [
        "Napa Valley",
        "Sonoma",
        "Paso Robles",
        "Willamette Valley",
        "Walla Walla",
        "Columbia Valley",
        "Santa Barbara",
        "Lodi",
        "Finger Lakes",
        "Bordeaux",
        "Burgundy",
        "Champagne",
        "Rhône Valley",
        "Loire Valley",
        "Alsace",
        "Languedoc",
        "Provence",
        "Tuscany",
        "Piedmont",
        "Veneto",
        "Sicily",
        "Puglia",
        "Rioja",
        "Ribera del Duero",
        "Priorat",
        "Rueda",
        "Barossa Valley",
        "McLaren Vale",
        "Margaret River",
        "Marlborough",
        "Central Otago",
        "Hawke's Bay",
        "Mendoza",
        "Maipo Valley",
        "Casablanca Valley",
        "Stellenbosch",
        "Mosel",
        "Rheingau",
        "Pfalz",
        "Douro Valley",
        "Other"
    ]
}
